_target_: model.custom_cnn.CustomCNNModel
input_width: 16
input_channels: 3
output_size: 10
cnn_layers: [16]
kernel_sizes: [5]
activ_fn: "relu"
criterion: "bce"
optimizer: 
  _target_: torch.optim.SGD
  lr: 0.03