trainer:
  max_epochs: 100
  gpus: 0
  progress_bar_refresh_rate: 100
  log_every_n_steps: 10
  # auto_lr_find: True

callbacks:
  checkpoint:
    monitor: val_loss
  early_stopping:
    monitor: val_loss
       
logger:
  _target_: pytorch_lightning.loggers.WandbLogger 
  project: advanced_dl
  name: debug

defaults:
  - datamodule: spiral
  - model: custom_fc