trainer:
  max_epochs: 100
  gpus: 1
  progress_bar_refresh_rate: 100
  log_every_n_steps: 10

callbacks:
  checkpoint:
    monitor: val_acc
  early_stopping:
    monitor: val_acc
       
logger:
  _target_: pytorch_lightning.loggers.WandbLogger 
  project: advanced_dl
  name: debug

defaults:
  - datamodule: spiral
  - model: custom_fc